"""
Anomaly Detector — Unsupervised Outlier Detection
====================================================
Uses Isolation Forest (sklearn) to detect anomalous sensor readings
without requiring labelled data.  Trained on 'normal' operating data
generated by MockPLCGenerator.

Can also compute a multivariate Mahalanobis distance for interpretability.

Features: temperature, vibration, current, pressure, speed, cycle_time
"""

import logging
import os
import pickle
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

logger = logging.getLogger(__name__)

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.covariance import EllipticEnvelope


# --------------------------------------------------------------------------
# Paths & constants
# --------------------------------------------------------------------------

MODEL_PATH   = Path(__file__).parent / "models" / "anomaly_detector.pkl"
FEATURE_COLS = ["temperature", "vibration", "current", "pressure", "speed", "cycle_time"]
CONTAMINATION = 0.05   # expected fraction of anomalies in training data


# --------------------------------------------------------------------------
# Synthetic 'normal' training data
# --------------------------------------------------------------------------

def _generate_normal_data(n: int = 6_000) -> np.ndarray:
    rng = np.random.default_rng(99)
    return np.column_stack([
        rng.normal(45,  4,   n),      # temperature
        rng.normal(2.1, 0.4, n),      # vibration
        rng.normal(18,  2,   n),      # current
        rng.normal(6.0, 0.5, n),      # pressure
        rng.normal(3000, 150, n),     # speed
        rng.normal(45,  5,   n),      # cycle_time
    ])


# --------------------------------------------------------------------------
# Result container
# --------------------------------------------------------------------------

@dataclass
class AnomalyResult:
    machine_id:    str
    is_anomaly:    bool
    anomaly_score: float    # higher = more anomalous (Isolation Forest score shifted to [0,1])
    z_scores:      Dict[str, float]   # per-feature z-score magnitude
    timestamp:     float = 0.0

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = time.time()

    def to_dict(self) -> Dict:
        return {
            "machine_id":    self.machine_id,
            "is_anomaly":    self.is_anomaly,
            "anomaly_score": round(self.anomaly_score, 4),
            "z_scores":      {k: round(v, 2) for k, v in self.z_scores.items()},
            "timestamp":     self.timestamp,
        }


# --------------------------------------------------------------------------
# Anomaly Detector
# --------------------------------------------------------------------------

class AnomalyDetector:
    """
    Isolation Forest-based anomaly detector.

    Keeps a per-machine rolling window of recent readings to compute
    z-scores relative to the machine's own operating history.
    """

    def __init__(
        self,
        model_path: Optional[Path] = None,
        window_size: int = 30,
        threshold: float = 0.55,   # anomaly_score above this → anomaly
    ):
        self.model_path  = model_path or MODEL_PATH
        self.window_size = window_size
        self.threshold   = threshold
        self._model      = None
        self._scaler     = None

        # Per-machine history for local z-score calculation
        self._windows: Dict[str, List[List[float]]] = {}

        self._load_or_train()

    # ------------------------------------------------------------------
    # Model lifecycle
    # ------------------------------------------------------------------

    def _load_or_train(self) -> None:
        if self.model_path.exists():
            try:
                with open(self.model_path, "rb") as f:
                    saved = pickle.load(f)
                self._model  = saved["model"]
                self._scaler = saved["scaler"]
                logger.info(f"[AnomalyDetector] Loaded model from {self.model_path}")
                return
            except Exception as exc:
                logger.warning(f"[AnomalyDetector] Load failed: {exc} — retraining")

        self._train()

    def _train(self) -> None:
        logger.info("[AnomalyDetector] Training Isolation Forest …")
        X = _generate_normal_data()

        self._scaler = StandardScaler()
        X_scaled     = self._scaler.fit_transform(X)

        self._model = IsolationForest(
            n_estimators=200,
            contamination=CONTAMINATION,
            max_samples="auto",
            random_state=42,
            n_jobs=-1,
        )
        self._model.fit(X_scaled)

        self.model_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.model_path, "wb") as f:
            pickle.dump({"model": self._model, "scaler": self._scaler}, f)
        logger.info(f"[AnomalyDetector] Model saved → {self.model_path}")

    # ------------------------------------------------------------------
    # Detection
    # ------------------------------------------------------------------

    def _extract_features(self, reading: Dict) -> np.ndarray:
        return np.array([[
            reading.get("temperature", 45),
            reading.get("vibration",   2.1),
            reading.get("current",     18),
            reading.get("pressure",    6.0),
            reading.get("speed",       3000),
            reading.get("cycle_time",  45),
        ]])

    def _compute_z_scores(self, features: np.ndarray, machine_id: str) -> Dict[str, float]:
        """Z-scores relative to the machine's own recent history."""
        window = self._windows.get(machine_id, [])
        if len(window) < 5:
            return {col: 0.0 for col in FEATURE_COLS}

        arr = np.array(window)
        mean = arr.mean(axis=0)
        std  = arr.std(axis=0) + 1e-9
        z    = np.abs((features[0] - mean) / std)
        return dict(zip(FEATURE_COLS, z.tolist()))

    def detect(self, reading: Dict, machine_id: str = "") -> bool:
        """
        Quick boolean — True if anomaly detected.
        """
        mid = machine_id or reading.get("machine_id", "UNKNOWN")
        return self.detect_full(reading, mid).is_anomaly

    def detect_full(self, reading: Dict, machine_id: str = "UNKNOWN") -> AnomalyResult:
        """
        Full anomaly result including score and per-feature z-scores.
        """
        features = self._extract_features(reading)
        X_scaled = self._scaler.transform(features)

        # Isolation Forest raw score: negative means outlier
        raw_score    = float(self._model.decision_function(X_scaled)[0])
        # Normalise to [0, 1] where 1 = most anomalous
        anomaly_score = max(0.0, min(1.0, 0.5 - raw_score))

        is_anomaly = anomaly_score > self.threshold

        # Override for known faulted readings
        if reading.get("fault_code", 0) > 0:
            is_anomaly    = True
            anomaly_score = max(anomaly_score, 0.90)

        z_scores = self._compute_z_scores(features, machine_id)

        # Update rolling window
        buf = self._windows.setdefault(machine_id, [])
        buf.append(features[0].tolist())
        if len(buf) > self.window_size:
            buf.pop(0)

        return AnomalyResult(
            machine_id=machine_id,
            is_anomaly=is_anomaly,
            anomaly_score=round(anomaly_score, 4),
            z_scores=z_scores,
        )

    def detect_all(self, readings: Dict[str, Dict]) -> Dict[str, AnomalyResult]:
        """Detect anomalies for all machines in one snapshot."""
        return {mid: self.detect_full(r, mid) for mid, r in readings.items()}

    def retrain(self) -> None:
        self._train()
